[package]
name = "gecs"
version = "0.1.0"
authors = ["recatek"]
description = "A generated entity component system."
edition = "2021"
repository = "https://github.com/recatek/gecs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["ecs", "entity"]
categories = ["data-structures", "game-engines"]

[dependencies]
gecs_macros = { version = "0.1.0", path = "macros" }

paste = { version = "1.0" }
